// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFJ3enB5ibY51jqVq5a2Cv8uwjqXIlBo',
    appId: '1:257237337017:web:2d75ceba4e772230622c68',
    messagingSenderId: '257237337017',
    projectId: 'yazilimmuh-caef8',
    authDomain: 'yazilimmuh-caef8.firebaseapp.com',
    storageBucket: 'yazilimmuh-caef8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZaf7zBxeE_l8hYdqdNAo4NFmqgSur0KU',
    appId: '1:257237337017:android:a03132c98bcc2b0f622c68',
    messagingSenderId: '257237337017',
    projectId: 'yazilimmuh-caef8',
    storageBucket: 'yazilimmuh-caef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJDQfccYHR8y-jK5kLJXmD7pzH4sYMmA',
    appId: '1:257237337017:ios:a9111737e7ded721622c68',
    messagingSenderId: '257237337017',
    projectId: 'yazilimmuh-caef8',
    storageBucket: 'yazilimmuh-caef8.appspot.com',
    iosClientId: '257237337017-m699rnkjnofg73rfen2351in0eul9hdh.apps.googleusercontent.com',
    iosBundleId: 'com.kisacaberk.kisacaberkproje',
  );
}
